const allTags = [
    // Food-related tags
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
    "Dairy-Free",
    "Nut-Free",
    "Low-Carb",
    "Keto-Friendly",
    "Paleo",
    "Whole30",
    "Organic",
    "Sustainable",
    "Locally Sourced",
    "Non-GMO",
    "Fair Trade",
    "Sugar-Free",
    "Low-Fat",
    "High-Protein",
    "Raw",
    "Grain-Free",
    "Halal",
    "Kosher",
    // Cuisine-related tags
    "Italian",
    "Mexican",
    "Chinese",
    "Japanese",
    "Indian",
    "Thai",
    "Greek",
    "Mediterranean",
    "French",
    "Spanish",
    "Middle Eastern",
    // Meal-related tags
    "Breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Snack",
    "Appetizer",
    "Main Course",
    "Side Dish",
    "Dessert",
    "Beverage",
    "Cocktail",
    // Ingredient-related tags
    "Chicken",
    "Beef",
    "Pork",
    "Seafood",
    "Vegetables",
    "Fruits",
    "Grains",
    "Legumes",
    "Nuts",
    "Herbs",
    "Spices",
    "Dairy",
    "Eggs",
    "Tofu",
    "Tempeh",
    "Quinoa",
    "Rice",
    "Pasta",
    // Dietary preferences and restrictions
    "Pescatarian",
    "Flexitarian",
    "Low-Sodium",
    "Heart-Healthy",
    "Weight Loss",
    "Weight Gain",
    "Bodybuilding",
    // Lifestyle-related tags
    "Gluten Intolerant",
    "Lactose Intolerant",
    "Diabetic",
    "Ketogenic",
    "Intermittent Fasting",
    "Meal Prep",
    "Quick & Easy",
    "Budget-Friendly",
    // Miscellaneous tags
    "Family-Friendly",
    "Kid-Friendly",
    "Picnic",
    "Barbecue",
    "Holiday",
    "Seasonal",
    "Comfort Food",
    "Fusion",
    "Street Food",
    "Gourmet",
    "Homemade",
    "Restaurant",
    "Takeout",
    "Delivery",
    // Cuisines from foodTags
    'African', 'American', 'Asian', 'Caribbean', 'Chinese', 'European', 'French', 'Greek', 'Indian', 'Italian', 'Japanese', 'Korean', 'Latin American', 'Mediterranean', 'Mexican', 'Middle Eastern', 'Spanish', 'Thai', 'Vietnamese',
    // Dietary Preferences from foodTags
    'Soy-Free', 'Egg-Free', 'Low-Sodium', 'Keto', 'Soy', 'Peanuts', 'Tree Nuts', 'Wheat',
    // Meal Types from foodTags
    'Snack', 'Side Dish', 'Main Course', 'Shellfish', 'Game Meat', 'Noodles', 'Bread', 'Coconut Oil', 'Vegetable Oil', 'Pepper', 'Diabetic-Friendly', 'Renal-Friendly', 'Spicy', 'Savoury', 'Sweet', 'Sour', 'Umami', 'Bitter', 'Steamed', 'Boiled', 'Sauteed', 'Stir-Fried', 'Pressure Cooked',
    // Special Occasions from foodTags
    'Christmas', 'Thanksgiving', 'Easter', 'Halloween', 'Valentine\'s Day', 'Birthday', 'Anniversary', 'Potluck', 'Christmas', 'Thanksgiving', 'Easter', 'Halloween', 'Valentine\'s Day', 'Birthday', 'Anniversary', 'BBQ', 'Picnic', 'Potluck',
    // Miscellaneous from foodTags
    'Spicy', 'Savoury', 'Sweet', 'Sour', 'Umami', 'Bitter'
];


export default allTags;
